### ISSUE TITLE
Additional suggestions

### ISSUE THREAD

**Issue by jafingerhut** [adasomg/the-missing-clojure-intro#2]
Your README has several occurrences of version "1.1.0" for Clojure, which I would recommend against using, as incompatible changes have been made to Clojure since that version of about 7 or 8 years ago.

You mention Clojure version "1.8.0" in some places, and "1.9.0" in others.  It might be nice to use a consistent version number everywhere, e.g. "1.9.0" would be reasonable, but so would "1.10.0" since it is officially released now.

**Comment by adasomg** [comment]
Well spotted thanks. The thing about versions later than 1.8.0 is, the jar doesn't seem to be enough to start a REPL (need spec and some other stuff), so I guess I'll change everything to 1.8.0. Thoughts?

**Comment by jafingerhut** [comment]
Agreed that since there is no implementation of the tools.deps based `clj` or `clojure` scripts for Windows yet, that makes it more involved to demonstrate a `java` command line that invokes a Clojure REPL, without using Leiningen.  With Leiningen it is pretty straightforward to run later versions, since it will automatically download the other necessary JARs for you.

**Comment by adasomg** [comment]
OK, going with 1.8.0 everywhere and I'll add a footnote discussing this.

Mind if I mention you in `Credits` at the end for helping out?

**Comment by jafingerhut** [comment]
I do not mind if you wish to mention me in the credits.  I am not helping very much, honestly :)

**Comment by jafingerhut** [comment]
In your footnote, you may want to mention that if they read about Clojure Spec and want to try it out, they will have an easier time using Leiningen and upgrading to the latest Clojure 1.10.0 release by editing the version of Clojure in their project.clj file, and that the way of starting Clojure via the example `java` command lines you show will no longer work without adding more JAR files to the class path.

**Comment by adasomg** [comment]
803ab79bd12e79fa7048362bf28d2aff91582e6a

**Comment by jafingerhut** [comment]
Looks like a good explanation to me.  Thanks.
